# Generated by Django 2.1 on 2020-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloguser', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('blog', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
